name: Docker build Python and push

on:
  push:
    branches: [ master, docker-action-dev ]

jobs:
  lapack:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Check Out Repo 
        uses: actions/checkout@v2
      -
        name: Build fuzzy lapack docker and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./fuzzy/docker/base/Dockerfile.ubuntu20.04-lapack
          push: true
          tags: yohanchatelain/fuzzy:lapack-v0.4.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  python:
    needs: lapack
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Check Out Repo 
        uses: actions/checkout@v2
      -
        name: Build fuzzy Python docker and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./fuzzy/docker/level1/Dockerfile.ubuntu20.04-python
          push: true
          tags: yohanchatelain/fuzzy:python-v0.4.1
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
