name: Docker Image CI

on:
  push:
    branches: [ master, docker-action-dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image fuzzy
      run: docker build . --file fuzzy/docker/level1/Dockerfile.ubuntu20.08-python --tag fuzzy
