name: ci

on:
  push:
    branches: [ master, docker-action-dev ]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build python and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: fuzzy/docker/level1/Dockerfile.ubuntu20.08-python
          push: true
          tags: yohanchatelain/fuzzy:python-latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
